# Домашнее задание №1

## Работа с модулем math

In [1]:
import math

In [5]:
a = 16
math.sqrt(a) #извлечение квадратного корня

4.0

In [10]:
a = 4.2
math.ceil(a) #округление вверх до ближайшего целого

5

In [12]:
a = 5.8
math.floor(a) #округление вниз до ближайшего целого числа

5

In [14]:
a = 5
b = 2
math.pow(a, b) #возведение в степень

25.0

In [17]:
a = 125
b = 1/3
math.pow(a, b)

4.999999999999999

In [19]:
c = 16
a = 4
math.log(c, a)

2.0

In [21]:
e = math.e
e

2.718281828459045

In [22]:
pi = math.pi
pi

3.141592653589793

In [23]:
x = pi/6
math.sin(x)

0.49999999999999994

In [25]:
x = pi/3
math.tan(x)

1.7320508075688767

In [26]:
a = 4
math.factorial(a)

24

In [29]:
a = 15
math.exp(a)

3269017.3724721107

In [31]:
math.degrees(pi/3) #преобразование радиан в градусы

59.99999999999999

In [33]:
math.radians(30) #преобразование радиан в градусы

0.5235987755982988

## Работа с модулем numpy

## Создание массивов, нахождение размерности

In [36]:
import numpy as np

In [51]:
b = np.array([1, 2, 3, 4]) #создание массива из списка

In [43]:
b

array([1, 2, 3, 4])

In [60]:
b.dtype #нахождение типа данных элементов массива

dtype('int64')

In [44]:
np.shape(b)

(4,)

In [39]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [40]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
np.shape(a) # вывод размерности массива

(2, 4)

In [48]:
np.zeros((3,4)) #создание двумерного массива из нулей

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.ones((3, 4, 5)) #создание трехмерногт массива из едениц

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [58]:
np.arange(10, 35, 5) #создание массив с заданным шагом

array([10, 15, 20, 25, 30])

In [120]:
np.empty((5,6)) #создание пустого массива

array([[8.14445751e-312, 1.02765654e-321, 0.00000000e+000,
        0.00000000e+000, 1.08221785e-312, 5.02034658e+175],
       [6.40321982e+170, 3.69927303e-033, 8.33087118e-071,
        5.39669235e-062, 7.79013422e-043, 7.75957928e-144],
       [3.59751658e+252, 3.96046095e+246, 1.04918621e-153,
        7.69165785e+218, 5.04621343e+180, 1.04917822e-153],
       [9.08366793e+223, 6.40321982e+170, 3.69927303e-033,
        8.33087118e-071, 5.39669235e-062, 1.04917593e-153],
       [1.94918966e-153, 9.72160709e-072, 2.26267501e-076,
        1.38133303e-047, 2.59027896e-144, 7.79952704e-143]])

In [122]:
np.eye(4) #создание единичной матрицы

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Индексы и срезы

In [61]:
a = np.array([6, 7 , 3, 1, 9, 0, 9])

In [62]:
a

array([6, 7, 3, 1, 9, 0, 9])

In [65]:
a[3] #нахожение 4 элемента массива(индекс 3, т.к. нумерация с 0)

np.int64(1)

In [68]:
a[2:5] #использование срезов

array([3, 1, 9])

In [72]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [73]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [89]:
b[1,3] #элемент из строки с индексом 1 и столбца с инлексом 3

np.int64(8)

In [85]:
b[(1,3)]

np.int64(8)

In [90]:
b[[1, 3]] #строки с индексами 1 и 3

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])

In [87]:
b[[1,3], 1] #элемент с индексом 1 из строки с инлексом 1 и элемент из строки с индесом 3 из строки с идексом 3

array([ 6, 14])

In [91]:
b[[1,3], [1,3]] #элемент с индексом 1 из строки с игдексом 1 и элемент с идексом 3 из строки с индексом 3

array([ 6, 16])

In [92]:
b[:, 2] #выводи 3 столбец, берутся все строки и  из каждой строки 3 элемент(индекс 2)

array([ 3,  7, 11, 15])

In [93]:
b[1, :] #выводит 2 строку,берутся все столбцы и из каждого столбца 2 элемент(индекс 1)

array([5, 6, 7, 8])

In [80]:
b[1:3, :] #строки с 2 по 3 включительно и все столбцы

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
b[1:3, :][1] #строки с 2 по 3 включительно и все столбцы, затем из из полученной матрицы берется 2 строка(индекс 1)

array([ 9, 10, 11, 12])

In [96]:
b[:] #весь массив

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## Векторные операции и базовые статистики

In [99]:
a = np.array([15, 87, 33, 15, 10])

In [100]:
b = np.array([3, 6, 8, 1, 4])

In [101]:
a + b

array([18, 93, 41, 16, 14])

In [102]:
a - b

array([12, 81, 25, 14,  6])

In [103]:
a * b

array([ 45, 522, 264,  15,  40])

In [104]:
a / b

array([ 5.   , 14.5  ,  4.125, 15.   ,  2.5  ])

In [105]:
b ** 2

array([ 9, 36, 64,  1, 16])

In [106]:
a + 5

array([20, 92, 38, 20, 15])

In [107]:
a * 2

array([ 30, 174,  66,  30,  20])

In [108]:
a

array([15, 87, 33, 15, 10])

In [109]:
a.sum()

np.int64(160)

In [110]:
a.max()

np.int64(87)

In [111]:
a.min()

np.int64(10)

In [117]:
np.mean(a) #среднее

np.float64(32.0)

In [118]:
np.median(a) #медиана

np.float64(15.0)

In [123]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [124]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [126]:
a.transpose() #транспонирование матрицы

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [127]:
a.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

## Тригонометрические функции

In [128]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [129]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003],
       [-0.91113026, -0.83907153,  0.0044257 ,  0.84385396],
       [ 0.90744678,  0.13673722, -0.75968791, -0.95765948]])

In [130]:
np.tan(a)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00],
       [-3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
        -6.79971146e+00],
       [-4.52315659e-01,  6.48360827e-01, -2.25950846e+02,
        -6.35859929e-01],
       [ 4.63021133e-01,  7.24460662e+00, -8.55993401e-01,
         3.00632242e-01]])

In [131]:
np.arctan(a)

array([[0.78539816, 1.10714872, 1.24904577, 1.32581766],
       [1.37340077, 1.40564765, 1.42889927, 1.44644133],
       [1.46013911, 1.47112767, 1.48013644, 1.48765509],
       [1.49402444, 1.49948886, 1.50422816, 1.50837752]])

## Случайные числа

In [132]:
import random

In [133]:
np.random.sample()

0.6691065317205984

In [134]:
np.random.sample((3,4))

array([[0.19580687, 0.14715684, 0.53312746, 0.94878601],
       [0.51150384, 0.90892254, 0.09285683, 0.87545063],
       [0.71380899, 0.82051225, 0.61662623, 0.34014051]])

In [135]:
np.random.sample(7)

array([0.26122687, 0.00978234, 0.89704374, 0.76264314, 0.61385313,
       0.70179032, 0.77384166])

In [137]:
np.random.randint(4, 6, 7)

array([4, 4, 5, 4, 5, 4, 4], dtype=int32)

In [138]:
np.random.random_integers(4, 6, 7)

C:\Users\ivmsa\AppData\Local\Temp\ipykernel_17780\510251481.py:1: DeprecationWarning: This function is deprecated. Please call randint(4, 6 + 1) instead
  np.random.random_integers(4, 6, 7)


array([6, 6, 4, 6, 4, 4, 6], dtype=int32)